{ Brick palette data extracted from PALBRICK.$00 }

const
  Palbrick000Data: array[0..279] of Byte = (
    $FF, $FF, $FF, $FF, $FF, $E0, $E4, $E8, $EC, $F0, $E0, $E4, $E8, $EC, $F0, $E0,
    $E4, $E8, $EC, $F0, $E0, $E4, $E8, $EC, $F0, $E0, $E4, $E8, $EC, $F0, $FE, $FE,
    $FE, $FE, $FE, $FF, $FF, $FF, $FF, $FF, $EA, $EE, $F2, $E2, $E6, $EA, $EE, $F2,
    $E2, $E6, $EA, $EE, $F2, $E2, $E6, $EA, $EE, $F2, $E2, $E6, $EA, $EE, $F2, $E2,
    $E6, $FE, $FE, $FE, $FE, $FE, $FF, $FF, $FF, $FF, $FF, $E1, $E5, $E9, $ED, $F1,
    $E1, $E5, $E9, $ED, $F1, $E1, $E5, $E9, $ED, $F1, $E1, $E5, $E9, $ED, $F1, $E1,
    $E5, $E9, $ED, $F1, $FE, $FE, $FE, $FE, $FE, $FF, $FF, $FF, $FF, $FF, $EB, $EF,
    $F3, $E3, $E7, $EB, $EF, $F3, $E3, $E7, $EB, $EF, $F3, $E3, $E7, $EB, $EF, $F3,
    $E3, $E7, $EB, $EF, $F3, $E3, $E7, $FE, $FE, $FE, $FE, $FE, $FF, $FF, $FF, $FF,
    $FF, $E2, $E6, $EA, $EE, $F2, $E2, $E6, $EA, $EE, $F2, $E2, $E6, $EA, $EE, $F2,
    $E2, $E6, $EA, $EE, $F2, $E2, $E6, $EA, $EE, $F2, $FE, $FE, $FE, $FE, $FE, $FF,
    $FF, $FF, $FF, $FF, $EC, $F0, $E0, $E4, $E8, $EC, $F0, $E0, $E4, $E8, $EC, $F0,
    $E0, $E4, $E8, $EC, $F0, $E0, $E4, $E8, $EC, $F0, $E0, $E4, $E8, $FE, $FE, $FE,
    $FE, $FE, $FF, $FF, $FF, $FF, $FF, $E3, $E7, $EB, $EF, $F3, $E3, $E7, $EB, $EF,
    $F3, $E3, $E7, $EB, $EF, $F3, $E3, $E7, $EB, $EF, $F3, $E3, $E7, $EB, $EF, $F3,
    $FE, $FE, $FE, $FE, $FE, $FF, $FF, $FF, $FF, $FF, $ED, $F1, $E1, $E5, $E9, $ED,
    $F1, $E1, $E5, $E9, $ED, $F1, $E1, $E5, $E9, $ED, $F1, $E1, $E5, $E9, $ED, $F1,
    $E1, $E5, $E9, $FE, $FE, $FE, $FE, $FE
  );
